---
creation_rules:
  - path_regex: kubernetes/envs/secrets.sops.yaml
    age: >-
      age1era3hzg0t8susnx9k2eldx54nfz3rnzm5g9etmnvww06s0uj3gjqqxwg92
  - path_regex: kubernetes/envs/.*/secrets.sops.yaml
    age: >-
      age1era3hzg0t8susnx9k2eldx54nfz3rnzm5g9etmnvww06s0uj3gjqqxwg92
