---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whoami
  labels:
    helm.sh/chart: network-config-1.0.0
    app.kubernetes.io/name: network-config
    app.kubernetes.io/instance: whoami
    app.kubernetes.io/version: "{{ .Values.whoami.imageVersion }}"
    app.kubernetes.io/managed-by: Helm
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  labels:
    helm.sh/chart: network-config-1.0.0
    app.kubernetes.io/name: network-config
    app.kubernetes.io/instance: whoami
    app.kubernetes.io/version: "{{ .Values.whoami.imageVersion }}"
    app.kubernetes.io/managed-by: Helm
spec:
  rules:
    - host: "{{ .Values.whoami.url }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
    helm.sh/chart: network-config-1.0.0
    app.kubernetes.io/name: network-config
    app.kubernetes.io/instance: whoami
    app.kubernetes.io/version: "{{ .Values.whoami.imageVersion }}"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: network-config
    app.kubernetes.io/instance: whoami
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels:
    helm.sh/chart: network-config-1.0.0
    app.kubernetes.io/name: network-config
    app.kubernetes.io/instance: whoami
    app.kubernetes.io/version: "{{ .Values.whoami.imageVersion }}"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: network-config
      app.kubernetes.io/instance: whoami
  template:
    metadata:
      labels:
        app.kubernetes.io/name: network-config
        app.kubernetes.io/instance: whoami
    spec:
      serviceAccountName: whoami
      containers:
        - name: network-config
          image: "traefik/whoami:{{ .Values.whoami.imageVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources: 
            {{- toYaml .Values.whoami.quotas | nindent 12 }}
