---
thesis:
  #
  # Deploy Options
  #
  deployed: true
  deployType: custom

  #
  # Common info
  #
  name: thesis
  namespace: default

  #
  # Custom App Definition
  #
  pod_volumes: []

  containers:
    - name: thesis
      image: ghcr.io/bricemichalski/thesis:master
      ports:
        - containerPort: 80

  service_ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http

  tls:
    - hosts:
        - brice.michalski.fr
      secretName: thesis-cert

  ingress_rules:
    - host: brice.michalski.fr
      http:
        paths:
          - path: /mémoire
            pathType: Exact
            backend:
              service:
                name: thesis
                port:
                  number: 80
          - path: /memoire
            pathType: Exact
            backend:
              service:
                name: thesis
                port:
                  number: 80
