---
namespaces:
  - name: kube-network
    system: true
    quotas:
      requests:
        memory: 200Mi
        cpu: 200m
      limits:
        memory: 400Mi
        cpu: 400m
        pvcs: 5
        storage: 100Mi

  - name: kube-storage
    system: true
    disableQuotas: true

  - name: kube-monitor
    system: true
    quotas:
      requests:
        memory: 1400Mi
        cpu: 2
      limits:
        memory: 2200Mi
        cpu: 2400m
        pvcs: 5
        storage: 3Gi
