---
- hosts: all
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - ping:
      tags:
        - always

- hosts: all
  gather_facts: false
  name: Hardening
  roles:
    - roles/hardening
  tags:
    - hardening

- hosts: nfs
  gather_facts: false
  name: NFS for backup
  become: true
  roles:
    - geerlingguy.nfs
  tags:
    - nfs

- hosts: knode
  gather_facts: false
  name: Raw Kubernetes cluster
  become: true
  roles:
    - geerlingguy.containerd
    - geerlingguy.kubernetes
  tags:
    - kubernetes
    - kubernetes::cluster

- hosts: kmaster
  gather_facts: false
  name: Install k9s & fetch kubeconfig
  become: true
  tasks:
    - include_tasks: tasks/kadmin.yml

    - name: Download k9s tarball
      get_url:
        url: "https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_x86_64.tar.gz"
        dest: "/tmp/k9s_{{ k9s_version }}_Linux_x86_64.tar.gz"
      register: k9s_archive

    - name: Unarchive k9s
      unarchive:
        src: "/tmp/k9s_{{ k9s_version }}_Linux_x86_64.tar.gz"
        dest: "/usr/local/bin"
        mode: 0755
        remote_src: true
      when: k9s_archive.changed
  tags:
    - kubernetes
    - kubernetes::k9s
    - kubernetes::kubeconfig
