---

- hosts: all
  gather_facts: true
  any_errors_fatal: true
  tasks:
    - ansible.builtin.ping:

    - ansible.builtin.debug:
        msg: "{{ ansible_hostname }} -> {{ansible_default_ipv4.address }}"
