---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-backup
  namespace: kube-storage
spec:
  name: daily-backup
  task: backup
  concurrency: 1
  cron: 30 1 * * *
  groups:
    - daily-backup-group
  labels:
    frequency: daily
  retain: 7
