---
namespaces:
  - name: kube-network
    system: true
    quotas:
      requests:
        memory: 300Mi
        cpu: 300m
      limits:
        memory: 500Mi
        cpu: 500m
        pvcs: 5
        storage: 200Mi

  - name: kube-storage
    system: true
    disableQuotas: true

  - name: kube-monitor
    system: true
    quotas:
      requests:
        memory: 1400Mi
        cpu: 2
      limits:
        memory: 3Gi
        cpu: 3
        pvcs: 5
        storage: 3Gi

  - name: data-store
    quotas:
      requests:
        memory: 2Gi
        cpu: 2
      limits:
        memory: 3Gi
        cpu: 3
        pvcs: 5
        storage: 5Gi

  - name: iam
    system: true
    quotas:
      requests:
        memory: 1024Mi
        cpu: 600m
      limits:
        memory: 1024Mi
        cpu: 800m
        pvcs: 5
        storage: 10Gi
