secrets:
    storage:
        ip: ENC[AES256_GCM,data:e5Re8fmpH7I4YttDFw==,iv:eoqgqhrnhA6skl2EceY21eDpTSXM1fJjhKIndXwNISM=,tag:4PYSOByNt/vhQ4Uz/HI50A==,type:str]
        port: ENC[AES256_GCM,data:gNw=,iv:YUzHZO1Oh31/ZT7busfqT//c50lkq8TBELY4qgACXik=,tag:ih9ANstVyAS1leP84NApWQ==,type:int]
        api_key: ENC[AES256_GCM,data:FLxocRFo29qd6A==,iv:tiEoJYIasG9FGMb/Kj9D9bz2jur9Q3JNWuHLeHVjr/U=,tag:fbV7yQ/9wNXKOMLI5PTnFw==,type:str]
    admin:
        username: ENC[AES256_GCM,data:PpFH46A=,iv:O69uwFmtuZoi5grbjzh5T6KC5gkIzkq5CTmbYv0aUbk=,tag:sY7XctYws6kTASiXlBJrGQ==,type:str]
        password: ENC[AES256_GCM,data:tZ7DtHGdCWA=,iv:+JGok0eIP+mj71sPjYt1iem1m8rm780YklIQSii9smM=,tag:N7rmcI4kzx59CZQi0EhlTQ==,type:str]
    keycloak:
        adminUsername: ENC[AES256_GCM,data:I/KYWXg=,iv:JHCRU9RiEx46SWBO0zeBvjsc82Qicpmqee5r+czdcjw=,tag:wbtCu4Ubi20Uzyfc9JYNLQ==,type:str]
        adminPassword: ENC[AES256_GCM,data:e9c85TTDFKE=,iv:oINMAGxuWvKbSZDeuuy7H9bQh8Jfm+55n0rxspiTvf0=,tag:odovAfxI8dU0hYXR5dSgKw==,type:str]
        dbAdminUsername: ENC[AES256_GCM,data:dZQGYDrGZ5lpKvcNUOw2WA==,iv:JDrl6b6CPTtSgvpIKm1g/73/3raftgiVMyb7+nPn7RM=,tag:LA8YZd3j9AWXYFE4hSs3oQ==,type:str]
        dbAdminPassword: ENC[AES256_GCM,data:4pOP/GfwGPndekrDOaqP1qT7kE1V,iv:LSy8peUW3jwtYX29vVD8n27FiTR6lA92FkvQX940Z+4=,tag:pbEUfUxGrxR5BZ0ReYRJ9A==,type:str]
    telegram:
        alertbot:
            token: ENC[AES256_GCM,data:hJ0zO4R1ARquR73xUfdjkcq2+Rtz7kjaqllL374G5avQmMbQfOR2o5yfEzncPA==,iv:xCohsGlR+DzbGhe5Edfh3S1SQ4FQQYXBTGKvyZTwa4s=,tag:uQBWVOYwup48ldgzw0o1PQ==,type:str]
            chatid: ENC[AES256_GCM,data:sIV4uOpB6jcurQ==,iv:D/p3y48tqrLA/0sabzbeUyLyqr4RUdgxnv+j3EIlzrk=,tag:6csV6Yk00XSlaEBHuGmrbA==,type:int]
    akhq:
        signatures: ENC[AES256_GCM,data:ro/nABLtAxhtXipBp0GGIy+7UZ13sdG354+oMsQRE6LM91iIC4qdIhRPY9yh1GwpxCdtVHtsAz0cmnTnc3VIa3kgQviRKOlMEpwTcUuWMgtxhBwYaFRwRA==,iv:BtO04k7dVLe5McfQtcX6rgAnZ29EYa6QxbMX5BIVKcg=,tag:9Pkx/TL5YSDX1ENTfD0InQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1era3hzg0t8susnx9k2eldx54nfz3rnzm5g9etmnvww06s0uj3gjqqxwg92
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtY21tcDdneU50TWN0SXpX
            RE1UVWJPMlQ2Y25nbE9EOGZjMVZwNjJVYndRCmo1bE1qNzJhSmpYNFg1dEYrV3h5
            UnFpaWdVN0ZCb2RubnVudHgxdGdLbWcKLS0tIGZDd1VYV2pHSXhTSnkxa2p0Y3dm
            Ly9oa0huQ1FrTWJHdDZqcVY5Y0R5T2MKqZzHaN8w3+Wd+kl+8uif+MxHGme6DGi7
            VnynDaiZPjSGNXxSZKSTx0HI0aRJGALo4XvYqLOuFRK2CWMAFuQAiw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1esy3q6tfujl43w3l887lwyr2g0h25ypc0glwhaeprdtztcndxs6qqstvu5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJR29PT1Ayc1Z6UEdibWUv
            aDBOTnNJRFA0cDZqRHNnZnBEQVhLT21uUHpFClczaHNWVmxCSCtDRS9CcWpKWXhK
            WUp3YjcyNXgveEF3UnZvQ2RGN0VHYUkKLS0tIGNkaWdORDBTakJzTjVRQzhpV3ph
            TVZackNwb3JnZkxMYXVuUkZ2bFovVEEK8N6euDfqr/2xbJRYjasQHsN/k/UN1oqm
            1NkEXKwSH/FreDXVeSRIFKSqA6bWYqIdZhJF7I/8JeYqFgt2ETYYPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-23T21:36:02Z"
    mac: ENC[AES256_GCM,data:I37aM9iSaMtgywss0MroR2SH2sFLy+K6cW3V+txQLi4LzOCQJfol9ve6+zhT8V4lTTmysNRiohSIheZqaYyNUwFVCc0IctcsmXHTvWepw+M+BM+9POuqV5MrnDr9F4r692iGFIb5ImpQ5FV8kQqXcn9vW+6sgQYsZaTbnAi83uk=,iv:mwDdlxnPjLrrQsj8l09e7mphLD2bcvEit+CqXCKCeIc=,tag:9OSYzBQwj934WtMiYHuhYw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
