---
namespaces:
  - name: kube-network
    system: true
    quotas:
      requests:
        memory: 500Mi
        cpu: 500m
      limits:
        memory: 800Mi
        cpu: 800m
        pvcs: 5
        storage: 200Mi

  - name: kube-storage
    system: true
    disableQuotas: true

  - name: kube-monitor
    system: true
    quotas:
      requests:
        memory: 1400Mi
        cpu: 2
      limits:
        memory: 3Gi
        cpu: 3
        pvcs: 5
        storage: 110Gi

  - name: data-store
    quotas:
      requests:
        memory: 2Gi
        cpu: 2
      limits:
        memory: 3Gi
        cpu: 3
        pvcs: 5
        storage: 5Gi

  - name: home
    system: false
    quotas:
      requests:
        memory: 200Mi
        cpu: 200m
      limits:
        memory: 200Mi
        cpu: 200m
        pvcs: 1
        storage: 200Mi
