---
namespaces:
  - name: kube-network
    system: true
    quotas:
      requests:
        memory: 500Mi
        cpu: 500m
      limits:
        memory: 800Mi
        cpu: 800m
        pvcs: 5
        storage: 200Mi

  - name: kube-storage
    system: true
    disableQuotas: true

  - name: kube-monitor
    system: true
    quotas:
      requests:
        memory: 1400Mi
        cpu: 2
      limits:
        memory: 3Gi
        cpu: 3
        pvcs: 5
        storage: 30Gi
