namespaces:
  - name: kube-network
    system: true
    disableQuotas: true

  - name: kube-storage
    system: true
    disableQuotas: true

  - name: kube-access
    system: true
    disableQuotas: true

  - name: kube-monitor
    system: true
    quotas:
      requests:
        memory: 1800Mi
        cpu: 2
      limits:
        memory: 3Gi
        cpu: 3
        pvcs: 5
        storage: 110Gi

  - name: extra-operator
    quotas:
      requests:
        memory: 2Gi
        cpu: 2
      limits:
        memory: 3Gi
        cpu: 3
        pvcs: 5
        storage: 5Gi

  - name: mbcaas-tools
    system: false
    disableQuotas: true
