---
quotas:
  traefik:
    requests:
      memory: 100Mi
      cpu: 200m
    limits:
      memory: 500Mi
      cpu: 400m
  whoami:
    requests:
      memory: 50Mi
      cpu: 100m
    limits:
      memory: 100Mi
      cpu: 200m
