---
- name: Install MetalLb
  become: true
  block:
    - name: Install metallb helm repository
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: "{{ metallb_charts_url }}"

    - name: Install metallb helm charts
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        values: "{{ lookup('template', 'metallb-config.yaml.j2') | from_yaml }}"
        release_namespace: "{{ kube_core_namespace }}"
        wait: yes

  tags:
    - kubernetes
    - kubernetes::metallb

- name: Install Traefik Ingress Controller
  become: true
  block:
    - name: Install traefik helm repository
      kubernetes.core.helm_repository:
        name: traefik
        repo_url: "{{ traefik_charts_url }}"

    - name: Install traefik helm charts
      kubernetes.core.helm:
        name: traefik
        chart_ref: traefik/traefik
        release_namespace: "{{ kube_core_namespace }}"
        values: "{{ lookup('template', 'traefik/config.yaml.j2') | from_yaml }}"
        wait: yes
   
    - name: Traefik Atomic Middleware
      kubernetes.core.k8s:
        state: present
        apply: yes
        definition: "{{ lookup('template', 'traefik/middleware/atomic/' ~ item ~ '.yml.j2') }}"
        wait: yes
      loop:
        - "admin-auth"
        - "compress"
        - "errors"
        - "https"
        - "ip-whitelist"
        - "ratelimit"
        - "x-forwarded-proto-https"

    - name: Traefik Chained Middleware
      kubernetes.core.k8s:
        state: present
        apply: yes
        definition: "{{ lookup('template', 'traefik/middleware/' ~ item ~ '.yml.j2') }}"
        wait: yes
      loop:
        - "security"
        - "common"
        - "admin"

    - name: Deploy traefik dashboard
      kubernetes.core.k8s:
        state: present
        apply: yes
        definition: "{{ lookup('template', 'traefik/dashboard.yaml.j2') }}"
        wait: yes

  tags:
    - kubernetes
    - kubernetes::core
    - kubernetes::core::traefik

- name: Deploy whoami app
  vars:
    app: "{{ whoami }}"
  import_role:
    name: roles/kube-apps
    tasks_from: custom
  tags:
    - kubernetes
    - kubernetes::core
    - kubernetes::core::whoami

- name: Install Custom Error Page
  become: true
  block:
    - name: Install k8s-at-home repository
      kubernetes.core.helm_repository:
        name: k8s-at-home
        repo_url: https://k8s-at-home.com/charts/

    - name: Install error-pages
      kubernetes.core.helm:
        name: error-pages
        chart_ref: k8s-at-home/error-pages
        release_namespace: "{{ kube_core_namespace }}"
        values: "{{ lookup('template', 'error.yml.j2') | from_yaml }}"
        wait: yes

  tags:
    - kubernetes
    - kubernetes::errorpages
