---
- name: Install Portainer
  become: true
  block:
    - name: Install portainer repository
      kubernetes.core.helm_repository:
        name: portainer
        repo_url: https://portainer.github.io/k8s/

    - name: Install portainer charts
      kubernetes.core.helm:
        name: portainer
        chart_ref: portainer/portainer
        release_namespace: "{{ kube_core_namespace }}"
        values: "{{ lookup('template', 'portainer/portainer.yml.j2') | from_yaml }}"
        wait: yes

    - name: Portainer ingress
      kubernetes.core.k8s:
        state: present
        apply: yes
        definition: "{{ lookup('template', 'portainer/portainer-ingress.yml.j2') }}"
        wait: yes

  tags:
    - kubernetes
    - kubernetes::core
    - kubernetes::core::portainer
