---
- name: Grant admin rights to Kubernetes
  become: true
  block:
    - name: Create .kube folder in home
      file:
        path: "/home/{{ cluster_admin }}/.kube"
        state: directory
        owner: "{{ cluster_admin }}"
        group: "{{ cluster_admin }}"
        mode: 0700

    - name: Copy root kubeconfig file
      copy:
        src: /root/.kube/config
        dest: "/home/{{ cluster_admin }}/.kube/config"
        remote_src: yes
        owner: "{{ cluster_admin }}"
        group: "{{ cluster_admin }}"
        mode: 0600

    - name: Set KUBECONFIG env var in .bashrc
      lineinfile:
        path: "/home/{{ cluster_admin }}/.bashrc"
        regexp: "^export KUBECONFIG="
        line: "export KUBECONFIG=/home/{{ cluster_admin }}/.kube/config"

    - name: Fetch kubeconfig
      ansible.builtin.fetch:
        src: "/root/.kube/config"
        dest: "../../../kubeconfig-{{ env }}"
        flat: yes
