---
phppgadmin:
  deployed: true

  #
  # Meta
  #
  name: postgres-admin-ui
  namespace: "{{ kube_data_namespace }}"

  #
  # Middleware
  #
  traefik_middleware: "common"

  #
  # App
  #
  pod_volumes: []

  containers:
    - name: phppgadmin
      image: docker.io/bitnami/phppgadmin:7
      ports:
        - containerPort: 8080
      env: 
        - name: DATABASE_HOST
          value: postgresql
          
  service_ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http

  tls:
    - hosts:
        - "{{ postgres_admin_domain }}"
      secretName: "{{ postgres_admin_domain }}-tls"

  ingress_rules:
    - host: "{{ postgres_admin_domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: postgres-admin-ui
                port:
                  number: 80
