---
whoami:
  deployed: true

  #
  # Meta
  #
  name: whoami
  namespace: "{{ kube_core_namespace }}"

  #
  # Middleware
  #
  traefik_middleware: "common"

  #
  # App
  #
  pod_volumes: []

  containers:
    - name: whoami
      image: containous/whoami
      ports:
        - containerPort: 80

  service_ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http

  tls:
    - hosts:
        - "{{ request_debug_domain }}"
      secretName: "{{ request_debug_domain }}-cert"

  ingress_rules:
    - host: "{{ request_debug_domain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80
