---

releases:
  version:
    traefik: v10.24.3
    cert-manager: 1.9.1
    error-pages: 1.2.2
    network-config: 1.1.0
    longhorn: 1.3.1
    prometheus-stack: 40.1.0
  installed:
    traefik: true 
    cert-manager: true
    error-pages: true
    network-config: true
    longhorn: true
    prometheus-stack: true

apps:
  version:
    traefik: v2.9
    errorPages: 2.18.0 
    whoami: v1.8.6
    alertManager: v0.24.0

quotas:
  traefik:
    requests:
      memory: 100Mi
      cpu: 200m
    limits:
      memory: 500Mi
      cpu: 400m
  whoami:
    requests:
      memory: 50Mi
      cpu: 100m
    limits:
      memory: 100Mi
      cpu: 200m

dns:
  target: ipv4.mbcaas.com
  traefik: router.mbcaas.com
  whoami: whoami.mbcaas.com
  errorPages: error.mbcaas.com
  longhorn: storage.mbcaas.com
  alertManager: alert.mbcaas.com