secrets:
    grafana:
        adminPassword: ENC[AES256_GCM,data:rvQi1n91lss=,iv:EtuYIRtKuSnKedNQlwWdR8bOb4ROLN7quwzurTbSrgc=,tag:LLib7soCJh8j4+GIMOKPyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mca6v8dp928affujurk4v84czk4mdstlvjtfk43apqy2kcxtvy5qmtt4h6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIU0R1TjRkcEhlVmk1eUNK
            bmJUaGIwQzBULzJwTWFIN3dnbFpKbW9ydFgwClgwL2c2TmM2ZThFMk9wV1BkVnFC
            bUdRb1JsM1RxR3A0WlM3YWhwM3NQeE0KLS0tIDVJRHpCL3Uvb3MwNUdQdUExbEJk
            blpobElOdGxYVEFFVlArTVlmTW8zWlkKDhtyrhV+mUiT+0TC9mw9tV8/X8DZZ6aK
            opSS3aLvtqI77XVnmXUCHKquvwdIEunZz8NMAs8r9RThlfHhEK3h7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-27T18:03:01Z"
    mac: ENC[AES256_GCM,data:6o62Ieu1S/h52klrd/Tn5kCgfNmlYB8mKF3q3HZprh8+ngFhzsaHGlxAGGta8WXiRupAg5PRcOxc7wGfAlo6f226GT2aW2Bu3LPO0Vt6vZ3DB6Rl6HYEO1LlKNCCX7cXwNqvb/daz+5wFGWxmU2Bo2rXNHqM8QJp43ZuhGrkwhw=,iv:T34EH5XXuesiJRFTnKdoJd+DsbmqoLfUfie7TUPOhBE=,tag:q7qUoeUiJ9AuiEnWN36dHA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
