---
{{ $envs := list "dev" "prod" }}
environments: 
{{- range $envs }}
  {{ . }}:
    values:
      - envs/commons.yml
      - envs/{{ . }}/env.yml
{{- end }}

helmDefaults:
  timeout: 600
  force: false
  createNamespace: false

repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik

  - name: jetstack 
    url: https://charts.jetstack.io


releases:
  - name: cert-manager
    namespace: kube-network
    chart: jetstack/cert-manager
    version: {{ .Values.charts.version.certmanager }}
    installed: {{ .Values.charts.installed.certmanager }}
    values:
      - modules/cert-manager.gotmpl

  - name: traefik-ingress-controller
    namespace: kube-network
    chart: traefik/traefik 
    version: {{ .Values.charts.version.traefik }}
    installed: {{ .Values.charts.installed.traefik }}
    values:
      - modules/traefik.gotmpl

  - name: traefik-config
    namespace: kube-network
    chart: ./charts/traefik-config
    version: 1.0.0
    installed: {{ .Values.charts.installed.traefik }}
    values:
      - modules/traefik-config.gotmpl
