---
{{ $envs := list "dev" "prod" }}
environments: 
{{- range $envs }}
  {{ . }}:
    values:
      - envs/commons.yml
      - envs/{{ . }}/env.yml
{{- end }}


helmDefaults:
  timeout: 600
  force: false
  createNamespace: false

repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik

releases:
  - name: traefik-ingress-controller
    namespace: kube-network
    chart: traefik/traefik 
    version: {{ $.Values.charts.version.traefik }}
    values:
      - modules/traefik.gotmpl

  - name: traefik-dashboard
    namespace: kube-network
    chart: ./charts/traefik-dashboard
    version: 1.0.0
    values:
      - modules/traefik-dashboard.gotmpl
