---
{{ $envs := list "dev" "prod" }}
environments: 
{{- range $envs }}
  {{ . }}:
    values:
      - envs/commons.yml
      - envs/{{ . }}/env.yml
{{- end }}

helmDefaults:
  timeout: 600
  force: false
  createNamespace: false

repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik

  - name: jetstack 
    url: https://charts.jetstack.io

  - name: k8s-at-home
    url: https://k8s-at-home.com/charts/


releases:
  - name: cert-manager
    namespace: kube-network
    chart: jetstack/cert-manager
    version: {{ .Values.charts.version.certManager }}
    installed: {{ .Values.charts.installed.certManager }}
    values:
      - modules/cert-manager.gotmpl

  - name: traefik
    namespace: kube-network
    chart: traefik/traefik 
    version: {{ .Values.charts.version.traefik }}
    installed: {{ .Values.charts.installed.traefik }}
    values:
      - modules/traefik.gotmpl

  - name: error-pages
    namespace: kube-network
    chart: k8s-at-home/error-pages
    version: {{ .Values.charts.version.errorPages }}
    installed: {{ .Values.charts.installed.errorPages }}
    values: 
      - modules/error-pages.gotmpl

  - name: network-config
    namespace: kube-network
    chart: ./charts/network-config
    version: 1.0.0
    installed: {{ .Values.charts.installed.networkConfig }}
    values:
      - modules/network-config.gotmpl
