---
{{ $envs := list "dev" "prod" }}
environments:
{{- range $envs }}
  {{ . }}:
{{- end }}

---
helmDefaults:
  timeout: 600
  force: false
  createNamespace: false

releases:
  - name: namespace
    namespace: kube-system
    chart: ./charts/namespaces
    values:
      - envs/{{ $.Environment.Name }}/namespaces.yaml
