---
{{ $envs := list "dev" "prod" }}
environments:
  {{- range $envs }}
  {{ . }}:
    values:
      - envs/commons.yml
      - envs/{{ . }}/env.yml
      - envs/{{ . }}/quotas.yml
    secrets:
      - envs/secrets.sops.yaml
      - envs/{{ . }}/secrets.sops.yaml
  {{- end }}

---

helmDefaults:
  timeout: 600
  force: false
  createNamespace: false

templates:
  default: &default
    missingFileHandler: Warn
    installedTemplate:  "{{`{{ .Values.releases.installed | get .Release.Name }}`}}"
    version: "{{`{{ .Values.releases.version | get .Release.Name }}`}}"
    values:
      - modules/{{`{{ .Release.Name }}`}}.gotmpl

repositories:
  - name: traefik
    url: https://helm.traefik.io/traefik

  - name: k8s-at-home
    url: https://k8s-at-home.com/charts

  - name: longhorn
    url: https://charts.longhorn.io

  - name: grafana
    url: https://grafana.github.io/helm-charts

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

  - name: bitnami
    url: https://charts.bitnami.com/bitnami

  - name: strimzi
    url: https://strimzi.io/charts/

  - name: akhq
    url: https://akhq.io/


releases:

  # Network
  - name: e-dns-cloudflare
    namespace: kube-network
    chart: bitnami/external-dns
    <<: *default

  - name: traefik
    namespace: kube-network
    chart: traefik/traefik
    <<: *default

  - name: error-pages
    namespace: kube-network
    chart: k8s-at-home/error-pages
    <<: *default

  - name: network-config
    namespace: kube-network
    chart: ./charts/network-config
    <<: *default

  # Storage
  - name: longhorn
    namespace: kube-storage
    chart: longhorn/longhorn
    <<: *default

  - name: storage-config
    namespace: kube-storage
    chart: ./charts/storage-config
    <<: *default

  # Observability
  - name: loki-stack
    namespace: kube-monitor
    chart: grafana/loki-stack
    <<: *default

  - name: prometheus-stack
    namespace: kube-monitor
    chart: prometheus-community/kube-prometheus-stack
    <<: *default

  - name: monitor-config
    namespace: kube-monitor
    chart: ./charts/monitor-config
    <<: *default

  # Data Store
  - name: strimzi-kafka-operator
    namespace: data-store
    chart: strimzi/strimzi-kafka-operator
    <<: *default

  - name: kafka-shared
    namespace: data-store
    chart: ./charts/kafka-shared
    <<: *default

  - name: akhq
    namespace: data-store
    chart: akhq/akhq
    <<: *default

  - name: keycloak
    namespace: iam
    chart: bitnami/keycloak
    <<: *default

  # APPS
  - name: ha-redirect
    namespace: home
    chart: ./charts/http-redirect
    <<: *default
