---
- name: Install Mysql Server
  become: true
  block:

    - name: Install db-operator repository
      kubernetes.core.helm_repository:
        name: db-operator
        repo_url: "{{ dboperator_charts_url }}"

    - name: Install DB opérator
      kubernetes.core.helm:
        name: db-operator
        chart_ref: db-operator/db-operator
        chart_version: "{{ db_operator_version }}"
        release_namespace: "{{ kube_data_namespace }}"
        values: "{{ lookup('template', 'db-operator.yml.j2') | from_yaml }}"
        wait: yes

    - name: "Deploy db instance"
      kubernetes.core.k8s:
        state: present
        apply: yes
        definition: "{{ lookup('template', item ~ '/instance.yml.j2' ) }}"
      loop:
        - mysql
        - pgsql
  
  tags:
    - kubernetes
    - kubernetes::data
    - kubernetes::data::pgsql