apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.name  | default .Release.name }}
  labels:
    {{- include "kafka-shared.labels" . | nindent 4 }}
spec:
  kafka:
    version: 3.4.0
    replicas: 1
    resources:
      {{- .Values.kafka.resources | toYaml | nindent 6 }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.4"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.kafka.storage.size }}
        class: {{ .Values.kafka.storage.class }}
        deleteClaim: {{ .Values.kafka.storage.deleteClaim }}
  zookeeper:
    replicas: 1
    resources:
      {{- .Values.zookeeper.resources | toYaml | nindent 6 }}
    storage:
      type: persistent-claim
      size: {{ .Values.zookeeper.storage.size }}
      class: {{ .Values.zookeeper.storage.class }}
      deleteClaim: {{ .Values.zookeeper.storage.deleteClaim }}
  entityOperator:
    topicOperator:
      resources:
        {{- .Values.topicOperator.resources | toYaml | nindent 8 }}
    userOperator:
      resources:
        {{- .Values.userOperator.resources | toYaml | nindent 8 }}
    tlsSidecar:
      resources:
        {{- .Values.tlsSidecar.resources | toYaml | nindent 8 }}
