---

- name: Deploy MBCaaS portal
  become: true
  block:

    - name: Install k8s-at-home repository
      kubernetes.core.helm_repository:
        name: k8s-at-home
        repo_url: https://k8s-at-home.com/charts/

    - name: Deploy favicon as configmap
      kubernetes.core.k8s:
        state: present
        apply: yes
        definition: "{{ lookup('template', 'portal-icon.yml') | from_yaml }}"

    - name: Install homer portal
      kubernetes.core.helm:
        name: homer
        chart_ref: k8s-at-home/homer
        release_namespace: "{{ kube_core_namespace }}"
        values: "{{ lookup('template', 'portal.yml.j2') | from_yaml }}"
        wait: yes
